#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "animation.h"


void animacao (void) {
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |/                   |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//                  |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |///                 |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |////                |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |/////               |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////              |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |///////             |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |////////            |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// /          |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// //         |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n"); 
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// ///        |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n") ;
    system("clear||cls");   
    printf("\n\n\n");
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// ////       |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|=============================================================================|\n");
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// /////      |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// //////     |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// ///////    |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// ////////   |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// /////////  |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// ////////// |     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    printf("\n");
    system("clear||cls");
    printf("\n\n\n");   
    printf("|======================================__=====================================|\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");
    printf("|                    ->     |//////// ///////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");   
    printf("|=============================================================================|\n");    
    auxTem2();
    system("clear||cls");
    printf("\n\n\n");       
    printf("|======================================  =====================================|\n");
    printf("|                                       /                                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");    
    printf("|                    ->     |//////// ///////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");    
    printf("|=============================================================================|\n");
    auxTem();
    system("clear||cls");;
    printf("\n\n\n");       
    printf("|===================================        ==================================|\n");
    printf("|                                   ===  ===                                  |\n");
    printf("|                                       |                                     |\n");
    printf("|                                                                             |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");    
    printf("|                    ->     |//////// ///////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");    
    printf("|=============================================================================|\n");
    auxTem();
    system("clear||cls");
    printf("\n\n\n");       
    printf("|================================              ===============================|\n");
    printf("|                                ===        ===                               |\n");
    printf("|                                   ===  ===                                  |\n");
    printf("|                                       |                                     |\n");
    printf("|                                       _                                     |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");    
    printf("|                    ->     |//////// ///////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");    
    printf("|=============================================================================|\n");
    auxTem();;
    system("clear||cls");
    printf("\n\n\n");       
    printf("|=============================                    ============================|\n");
    printf("|                             ===              ===                            |\n");
    printf("|                                ===        ===                               |\n");
    printf("|                                   ===  ===                                  |\n");
    printf("|                                         _                                   |\n");
    printf("|                    = = = = = Entrando/ na conta = = = = =                   |\n");
    printf("|                                                                             |\n");
    printf("|                           __________ ___________                            |\n");    
    printf("|                    ->     |//////// ///////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");    
    printf("|=============================================================================|\n");
    auxTem();
    system("clear||cls");
    printf("\n\n\n");       
    printf("|==========================                          =========================|\n");
    printf("|                          ===                    ===                         |\n");
    printf("|                             ===              ===                            |\n");
    printf("|                                ===        ===                               |\n");
    printf("|                                   ===  ===                                  |\n");
    printf("|                    = = = = = Entrando na conta = = = = =                    |\n");
    printf("|                                                                             |\n");
    printf("|                           __________/___________                            |\n");    
    printf("|                    ->     |//////// ///////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");    
    printf("|=============================================================================|\n");
    auxTem();
    system("clear||cls");
    printf("\n\n\n");       
    printf("|=======================                                ======================|\n");
    printf("|                       ===                          ===                      |\n");
    printf("|                          ===                    ===                         |\n");
    printf("|                             ===              ===                            |\n");
    printf("|                                ===        ===                               |\n");
    printf("|                    = = = = = Entra=== n===onta = = = = =                    |\n");
    printf("|                                   ndo  a c                                  |\n");
    printf("|                           __________ ___________                            |\n");    
    printf("|                    ->     |////////////////////|     <-                     |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");
    printf("|                                                                             |\n");    
    printf("|=============================================================================|\n");
    auxTem();


    printf("\n");
    printf("              .===================== Enter =====================.\n");
    printf("\n");
    getchar();
     
    }


void auxTem(void) {
    int i = 0;

    while (i <= 199999900) {
        i = i + 1;
    }
}

void auxTem2(void) {
    int i = 0;

    while (i <= 19900000) {
        i = i + 1;

    }
}